[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Kocevar <jonathan.kocevar@gmail.com>"]

[[bin]]
name = "day01"
path = "src/day01/day01.rs"

[[bin]]
name = "day02"
path = "src/day02/day02.rs"

[dependencies]